### ISSUE TITLE
Cant find 'Telerik' after rebuild all

### ISSUE THREAD

**Issue by Vejas04** [silahian/VisualHFT#19]
Hey, I'm new to this but I wasn't able to find the 'Telerik' folder after rebuilt all.
I also couldn't figure it out with the help of the Getting Started Guide. Any help is appreciated 🗡️

**Comment by silahian** [comment]
telerik libraries and dependencies have been removed several releases ago.

**Comment by Vejas04** [comment]
Thanks for the fast response. How should I proceed from now on? Unfortunately, I can't find the demoTradingCore in my VisualStudio project. Best Regards.

**Comment by silahian** [comment]
If you have the latest version, you won't need any reference to Telerik.
and the demoTradingCore project is located in https://github.com/silahian/VisualHFT/tree/master/demoTradingCore

**Comment by Vejas04** [comment]
Hey, thanks again! I'm able to run the program. However I get the following error when trying to reach new data:
![image](https://github.com/silahian/VisualHFT/assets/53182261/b0b44178-844c-4066-aaf6-9863f9be3748)

**Comment by silahian** [comment]
Since Telerik references are no longer needed I'm closing this issue.

**Comment by silahian** [comment]
Since Telerik references are no longer needed I'm closing this issue.
