### ISSUE TITLE
currently using Telerik Charts. Replace them with some good opensource WPF charts.

### ISSUE THREAD

**Issue by silahian** [silahian/VisualHFT#2]
Some good alternatives 

- ScottPlot 
- oxyplot

**Comment by eabase** [comment]
Here a re the links:

* https://github.com/oxyplot/oxyplot
* https://github.com/ScottPlot/ScottPlot

**Comment by drusteeby** [comment]
anyone working on this?

**Comment by silahian** [comment]
no one.
Feel free to contribute to that

**Comment by drusteeby** [comment]
I tried to create a branch to submit a PR but was permission denied. Could you give me permission to create a branch?

**Comment by ramateur** [comment]
ScottPlot does not support MVVM pattern, some code changes would be required. With oxyplot I managed to replace linear charts with just .xaml modification. Got stuck with buuble chart for now.

**Comment by silahian** [comment]
> Got stuck with buuble chart for now.

What about using oxyplot's ScatterSeries for that?

**Comment by ramateur** [comment]
> What about using oxyplot's ScatterSeries for that?

Yes, it exactly what is needed. Some modified .xamls in attachment. OxyPlot.Contrib.Wpf package via nuget is required. Style and scale improvements are needed.
[View.zip](https://github.com/silahian/VisualHFT/files/12013695/View.zip)

**Comment by ramateur** [comment]
What is the purpose of the PriceCharting form? It seems to repeat charts of the ucOrderBook component.

**Comment by silahian** [comment]
> What is the purpose of the PriceCharting form? It seems to repeat charts of the ucOrderBook component.
Yeah, that probably needs to go.

**Comment by silahian** [comment]
> Style and scale improvements are needed.

man, that looks great.. but yeah.. styling is needed!

**Comment by ramateur** [comment]
I changed appearence a little and switched solution to net60
![image](https://github.com/silahian/VisualHFT/assets/8994390/900bbda6-58d8-4e22-9b2a-1d1f78b025aa)

**Comment by ramateur** [comment]
Telerik components remain in AnalyticReports part for now. Will replace them soon.

**Comment by silahian** [comment]
Please, hold on... we are styling it and is getting much better

**Comment by silahian** [comment]
Ok, Thanks to @ramateur we changed charts in favor of OxyPlot
We have added some styles, but I think it could be improved even more.
The axis labels are one of the think we should improve (styling wise)

**Comment by drusteeby** [comment]
How is this code getting merged? For traceability and organization I would recommend that no code gets pushed into master unless it's through a PR approved by @silahian. Did @ramateur work on the code and send it to you somehow?

**Comment by silahian** [comment]
> How is this code getting merged?
That's the other thing I wanted to address. @ramateur sent me an attachment, and I reviewed the code, and made the proper changes.

So, @ramateur, next time let's follow the conventions here. Try to create a PR in order to push your contributions.

**Comment by drusteeby** [comment]
I will create a contributing guide, just opened an issue to remind myself.

**Comment by drusteeby** [comment]
Is there more code to be merged for this update? I ask because master is still using net48 not net6.0. Upgrading that was part of the cleanup tasks but if it's already done I don't want to do the work twice.

**Comment by silahian** [comment]
we haven't changed to net6.0, so still working on 4.8

**Comment by ramateur** [comment]
I followed contributing guide, cloned current repository to proceed working on replacing telerik components, but current version does not rescive any market updates from demoTradingCore.

**Comment by drusteeby** [comment]
Do you have the database set up?
https://github.com/silahian/VisualHFT/issues/6

**Comment by ramateur** [comment]
Yes, it was database issue. Forgot to change ConnectionStrings. Now works fine. Thank you.

**Comment by ramateur** [comment]
Telerik components remain in ucEquityChart.xaml and this view is not follow MVVM pattern. Also there is no data in DB to test it. This view prevents us from switching to net60 without installing telerik wpf6 components. How to deal with it?

**Comment by drusteeby** [comment]
Merge what you have done so far regardless, which is most of it. Maybe @silahian can chime in here.

**Comment by silahian** [comment]
First, thanks for the work.
I want to make sure we get rid of "all" telerik controls, and stick to oxyplot. So Please take the below instructions to be able to work on the equity chart.
Also, why you mentioned net60? I don't remember mentioning that, but just asking, Is there any good reason to move towards that?

Now, to the instructions to allow you to work on the Analytics form.
The Analytics form uses the [Position] table, which the trading system itself will fill out—in our case, "demoTradingCore" app. And also, it will depend on the "Session Date" we have (top right date-picker). By default, it is always today's date.
The position & execution data will be handled by vmPosition ViewModel. Currently is not fully working as supposed to. So I did some changes to allow us to see some positions in there.

I created a sql-script to fill out this table with dummy data, so you can test it that way (file is located [here](https://github.com/silahian/VisualHFT/blob/master/SQL%20scripts/Positions%20table%20dummy%20data.sql))
Once you got that data in your database, make sure to follow this steps:
1. After VisualHFT loads, select the date-pick to '2022-10-05'
2. Then change the date again to '2022-10-06'
3. Wait until you see the "EXECUTION" data grid fill out (shouldn't be more than 5 seconds)
4. Then, we are sure the position data is loaded, and you can launch the analytic window.

Hope all the above makes sense for now.
This week I will be working on the position usercontrol and ViewModel to make sure works as it is supposed to.
But, in the meantime, this is a quick workaround for the analytic form.

**Comment by drusteeby** [comment]
@silahian .net60 is the lastest version, it should improve performance quite a bit. 
https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/

Especially if NewtonSoft was replaced with System.Text.Json as that is documented to be much more performant in the latest .net versions
https://medium.com/@tobias.streng/net-performance-series-2-newtonsoft-vs-system-text-json-2bf43e037db0

**Comment by silahian** [comment]
> it should improve performance quite a bit.
That is good. I'm in with that.
Thanks for the clarification.

**Comment by silahian** [comment]
Thanks again @ramateur  for the PR
We finally can get rid of those Telerik charts, and have a better architecture.

**Comment by silahian** [comment]
I think we can close this one, right?

**Comment by ramateur** [comment]
Yes, we can
