### ISSUE TITLE
Bids and Asks arrays become unsorted after some time

### ISSUE THREAD

**Issue by ramateur** [silahian/VisualHFT#20]
Noticed that after some time Bids and Asks arrays become unsoted. It appears after switching to OrderBook popup window and back.
![image](https://github.com/silahian/VisualHFT/assets/8994390/56e78053-bf42-45b3-a7aa-65c287d5dc62)

**Comment by ramateur** [comment]
Fixed in PR https://github.com/silahian/VisualHFT/pull/21

**Comment by silahian** [comment]
PR applied. Great job
