### ISSUE TITLE
Extending OrderBook UC with additional depth views

### ISSUE THREAD

**Issue by ramateur** [silahian/VisualHFT#22]
What about extending OrderBook UC with additional switchable depth views?
![OrderBook1](https://github.com/silahian/VisualHFT/assets/8994390/b0cf2fe6-50ec-4e48-b6a0-a2d143c1abcb)

**Comment by silahian** [comment]
That is a great addition! I love it
Please create the PR

**Comment by ramateur** [comment]
Done in PR https://github.com/silahian/VisualHFT/pull/23

**Comment by silahian** [comment]
@ramateur there is a problem with the grid when it gets longer it will mess with the other controls.
We need to contain the height. Something similar we did with the "Trades" grid (the one at the right)
Can you take a look at that?

**Comment by ramateur** [comment]
OK, I'll fix it

**Comment by ramateur** [comment]
Fixed in PR #24
