### ISSUE TITLE
Website dead

### ISSUE THREAD

**Issue by azataiot** [silahian/VisualHFT#32]
https://www.visualhft.com/ 

responses with 504 Gateway Time-out.

**Comment by silahian** [comment]
Looks ok to me

**Comment by azataiot** [comment]
> Looks ok to me

Yes, it is now opening again. Please check the access and error logs, there must be something happen earlier.

**Comment by eabase** [comment]
@silahian 
Wow, cool website!

**Comment by silahian** [comment]
Thanks @eabase 
I'm looking forward to revamping the open-source version with better architecture and performance improvements.
So, very active months are coming for the project.
If you're still interested in collaborating let me know, that will be great!
