### ISSUE TITLE
Can't connect to coinbase

### ISSUE THREAD

**Issue by bhavyajain768** [silahian/VisualHFT#35]
Hi, I'm new to this and not able to retrieve data from coinbase. I did all the steps and was able to build the project but when I ran the demoTradingCore it shows "++ ATENTION: COINBASE DISCONNECTED or NO DATA...". I can't find where to change the api keys if that's the issue. Please let me know what I'm doing wrong.

![image](https://github.com/silahian/VisualHFT/assets/76229191/c3ccd88c-8c55-4fbf-8bab-46b0aea11a87)

**Comment by silahian** [comment]
You will need to debug and see what's the real reason.
