### ISSUE TITLE
How to use MS SQL Server 2019 Express with LocalDB (for demo data)

### ISSUE THREAD

**Issue by eabase** [silahian/VisualHFT#6]
MS `SQL Server 2019 Express` using the `LocalDB` install is only 58 MB. Saving huge effort and space. 

- [x] Provide installation instructions

**Comment by eabase** [comment]
#### Installation of `MS SQL Server 2019 Express`

Here we describe the method for installing the *MS SQL Server 2019 Express* with the `LocalDB` install option. This is only **58 MB*, so will save you a lot of time and d6 GB of storage space. It is assumed that you already have the latest versions of *Powershell, winget* and *nuget*, installed. (See the required installation instructions for details on these.)

**Requirements**
* `winget install Microsoft.PowerShell`
* `winget install Microsoft.NuGet `
* ``
* ``
* ``

Open a non-admin powershell:
```powershell
# Interactive install of the Express version 
winget install -i --id=Microsoft.SQLServer.2019.Express -e
```

This will open an standard interactive installation session, where you need to make some choices.

![image](https://user-images.githubusercontent.com/52289379/199987793-d8b2f33b-5257-4c88-b79d-628bf73ac907.png)

Alternatively (not using `winget`), you can download and run the same installer directly from [here](https://go.microsoft.com/fwlink/?LinkID=866658). 

For in order to have full control on what is happening I decided to select the `Download Media` option. I forgot to make all screenshots here, but I think you can also use the `Custom` option here. Either way, you should get a new screen that look like this: 

![image](https://user-images.githubusercontent.com/52289379/199996952-272e04c2-53d2-4f53-8d46-d51db6c7840e.png)

Here you select the `LocalDB` install, as the entire server engine is not needed. Selecting this option will download the installer to the selected directory. The downloaded file is called: `SqlLocalDB.msi`. (In case you select the `Express Core` option, the file will be called `SQLEXPR_x64_ENU.exe` @ 262 MB.)

Next, you run the installer `SqlLocalDB.msi`.

![image](https://user-images.githubusercontent.com/52289379/199998749-2df6a9c3-e9fc-4df0-aa4e-fb9d0f685f29.png)

`[Here I forgot to make proper screenshots...]`

Once installed, you can locate the executable tool:
```powershell
cd C:\Program Files\Microsoft SQL Server\150\Tools\Binn

.\SqlLocalDB.exe -?
.\SqlLocalDB.exe info

# Create the "hft" server instance
.\SqlLocalDB.exe create "hft"

# Start the "hft" server instance. 
# NOTE: The default timeout is 15 minutes( ?)  with no connections, before it shuts down automatically. 
.\SqlLocalDB.exe start "hft"

# Check the running status 
.\SqlLocalDB.exe info "hft"

Name:               hft
Version:            15.0.2000.5
Shared name:
Owner:              xxx\xxx
Auto-create:        No
State:              Running
Last start time:    2022-11-01 02:17:36 PM
Instance pipe name: np:\\.\pipe\LOCALDB#2619DE1D\tsql\query

# Stop the "hft" server instance:
.\SqlLocalDB.exe stop "hft"
```
❗ : **NOTE**: The named pipe gets a new name every now and then, so don't hard code this anywhere. 
Instead use the virtual named pipe with your server name: **`(localdb)/hft`**.  The default is `(localdb)/MSSQLLocalDB`.
When you create a server instance, you actually create a DB file that can also be used to connect to, instead of the name pipe. 
It is located (by default) in: `C:\User\UserName\hft.mdf`. We will show how this can be done in Visual Studio later. 

In order for this to do anything useful we need to create a database. To do this we need some tool to talk to the server instance. We can use either the tiny **`sqlcmd`** or the huge 676 MB *`Microsoft SQL Server Management Studio`* (**SMSS**). As I'm going for the minimalist approach here, I chose the former. So we need to install 2 more packages for this. The *sqlcmd* application itself, and the `ODBC` connector used by .NET and the VS etc. 

Download & Install them: 

* Download ODBC 17:
[msodbcsql.msi](https://go.microsoft.com/fwlink/?linkid=2200731) (~4.5 MB)

* Download sqlsmd 15: 
[MsSqlCmdLnUtils.msi](https://go.microsoft.com/fwlink/?linkid=2142258) (~2 MB)

I didn't find them as clear text winget packages, but the ODBC is named: `Microsoft ODBC Driver 17 for SQL Server`.

Now restart your shell.

```powershell
# Start the LocalDB server instance:
.\SqlLocalDB.exe start "hft"

# try sqlcmd to Check DB version info" 
sqlcmd -S "(localdb)\hft" -e -Q 'SELECT @@VERSION;'

# Create the "hft" DB (different from server instance):
sqlcmd -S "(localdb)\hft" -e -Q 'CREATE DATABASE hft;'

# Create the VisualHFT DB structure:
cd "C:\Users\xxx\dev\VisualHFT\SQL scripts"
sqlcmd -S "(localdb)\hft" -e -i '.\table creation.sql'

# You can now run any MS SQL queries like this: 
sqlcmd -S "(localdb)\hft" -Q ':Help' -u -W
sqlcmd -S "(localdb)\hft" -Q ':Listvar' -u -W
sqlcmd -S "(localdb)\hft" -Q "SELECT * FROM [hft].sys.tables;" -u -W
```

Using the .NET with LocalDB is as simple as changing the `App.config` to:
```xml
...
  <connectionStrings>
    <add name="HFTEntities" connectionString="metadata=res://*/Model.hftModel.csdl|res://*/Model.hftModel.ssdl|res://*/Model.hftModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=(LocalDB)\hft;AttachDbFilename=C:\Users\xxx\hft.mdf;initial catalog=hft;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />
  </connectionStrings>
  <appSettings>
    <add key="ConnectionString" value="Data Source=(LocalDB)\hft;AttachDbFilename=C:\Users\xxx\hft.mdf;Integrated Security=True;Connect Timeout=30;Initial Catalog=hft;MultipleActiveResultSets=True;Trusted_Connection=True" />
...
```

---

### Connecting to a LocalDB in VS 2019

***TBA***



---

#### Additional Info

And read more about it here.
* [Editions and supported features of SQL Server 2019 (15.x)](https://learn.microsoft.com/en-us/sql/sql-server/editions-and-components-of-sql-server-2019?view=sql-server-ver16)
* [Local Data Overview](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2012/ms233817(v=vs.110))












```

**Comment by drusteeby** [comment]
Got it working with these instructions, tyvm.

**Comment by ramateur** [comment]
What about DB settings to demoTradingCore? Are connection strings the same?

**Comment by silahian** [comment]
> Are connection strings the same?

yes, they should be the same.

**Comment by silahian** [comment]
Can we close this issue?

**Comment by ramateur** [comment]
I still have some misunderstanding about db relationship between demoTradingCore and visual part. Connection strings refer to different model names (dbEntities and HFTEntities). Also model diagrams differ in these projects.  When demoTradingCore tries to create position it falls with exception (System.Data.Entity.Core.MetadataException: 'Unable to load the specified metadata resource.'). Both connection strings point to the same local db.
![image](https://github.com/silahian/VisualHFT/assets/8994390/79f3ae0d-bd2a-4cb0-814f-3973983c6b0a)

**Comment by silahian** [comment]
> different model names

agree... something to improve. But the two are connecting to the same database.
Let me explain more. 
The data that needs to be persisted are the positions and their executions. Hence, demoTradingCore is the one it will write as they happen into the tables.
Then VisualHFT will read these tables, periodically using a timer. This is a part I also want to work on. We can improve this much better.
Having these positions, VisualHFT is able to calculate a bunch of analytics (and display them in the Analytics form). 

As per the error you displayed there, not sure why exactly. But to me, looks like a problem with your connection strings.
Keep in mind, that there are two connection strings:
![image](https://github.com/silahian/VisualHFT/assets/17384348/07b5d968-ce8e-464b-8998-7d5237f018ac)
The first is for the .NET entity framework, and the second is for general purposes. Both must point to the same db.

Hope this clarifies your problem

**Comment by drusteeby** [comment]
Might be a good spot to ask this: why is demoTradingCore a separate application from the main application? Is demoTradingCore meant to be replaced with another application in another use case?

**Comment by silahian** [comment]
> why is demoTradingCore a separate application from the main application?

Indeed a great question... and I'm being asked a lot about that. That's why I just updated the project's description a little bit to address that.

Anyways, I will tell you here: demoTradingCore is designed to act as a data provider, simulating trading data and feeding it to VisualHFT. It's essentially a mock trading engine for demonstration and testing purposes.
It also allows users to replace or modify the demoTradingCore with their own data provider if they wish, without affecting the main VisualHFT application. We have some production clients wanting to use VisualHFT with their internal systems. So those can feed with data VisualHFT

The main spotlight of this project is VisualHFT and its real-time analytics capabilities. demoTradingCore is just a supportive tool to feed it with necessary data.

**Comment by drusteeby** [comment]
Thanks for clarifying, follow up question:

"VisualHFT requires a specific collection of JSON data to function correctly. This data, which includes positions and executions, must be read from a Microsoft SQL Server database."

Would it make sense for positions and executions (and the other data) to also be fed to VisualHFT through websockets instead of routing through a database?

**Comment by silahian** [comment]
> Would it make sense for positions and executions (and the other data) to also be fed to VisualHFT through websockets instead

Not really, VisualHFT has been thought to be a client system, where multiple traders or analysts can connect and see what's going on in their trading operation. So It is a client system, and we cannot rely on the persistence of that data on this.

I also did more clarifications on the main readme,md related to this specific question:
```
VisualHFT operates by receiving a specific collection of JSON messages via WebSocket for real-time data. This data includes market data messages, exposures, and active orders statuses. In addition to this real-time data, VisualHFT also requires access to positions and executions data, which are read from a Microsoft SQL Server database. 

Together, these data sources allow VisualHFT to function correctly and provide a comprehensive view of trading operations."

In addition to receiving data, VisualHFT also can communicate with the core trading system via REST. This allows VisualHFT to send specific commands back to the core system, enabling it to control various aspects of the trading operation. For instance, VisualHFT can instruct the core system to start or stop trading, or to modify parameters of active strategies. 

This two-way communication ensures that VisualHFT not only visualizes trading operations but also has the ability to influence them based on user inputs or predefined conditions.

```

**Comment by drusteeby** [comment]
Right, I understand that VisualHFT is a client and won't be persisting that data, but why does VisualHFT have to read that data though a database instead of being fed the data through a websocket interface?

**Comment by silahian** [comment]
Well, remember that VisualHFT can go back in date and analyze past days. At least that was the initial idea, even though right now is not fully working. 
As per current days positions, we wanted to save real-time bandwidth and processing power to the market data only. Since it could become overwhelming.

**Comment by drusteeby** [comment]
Ok. I only bring it up because sending the data through websockets/REST could eliminate the dependency of VisualHFT on any sort of database. It doesn't have to be real time, it can be though the REST server portion. 

Using your diagram this is what I imagine:
![image](https://github.com/silahian/VisualHFT/assets/11130892/f6532c31-0b29-4604-83cd-931156dfd59c)

Then it wouldn't matter what type of persistence the Core Trading System uses, it can feed that data to VisualHFT through a common REST interface. 

Might be a big change but could be worth it to improve flexibility.

**Comment by silahian** [comment]
There is another important reason why we don't send position (and its executions) through the websockets.
In these type of systems (HFT) you may end up having anywhere from 1k to 10k positions per day. The whole json would be too big to send by the core trading system all the time.

However, I understand that the db part could be a drawback for some. So, maybe, one possibility is to have the ability to switch on/off the database, from settings.

**Comment by silahian** [comment]
I updated the Position classes now it should work properly.
While doing so, I remember that we initially thought of sending positions through WS, so you will see in the HelperPosition constructor the ability to choose to have positions between database or websocket. 

We could use that as a base to allow users to choose, as long as it can be set from the app.config. We even added a Position parser in the Helperwebsocket... so as long as we use the same model (and json message), it could work.
However, the entire flow should be tested, since it hasn't been used for that option forever.

**Comment by silahian** [comment]
Closing this since we are not dependent on DB anymore.
In case anyone needs to have a database for any reason, it could be added as a plugin instead.
